- name: Debug rke2_role value
  debug:
    msg: "The value of rke2_role is: {{ rke2_role }}"

- name: Install Cilium CLI
  include_tasks: cli.yaml
  when: rke2_role == "server" and cilium_install

# include tasks from config
- name: Configure Cilium
  include_tasks: config.yaml
  when: rke2_role == "server"

# install Helm chart
- name: Install Cilium Helm Chart
  include_tasks: helm.yaml
  when: rke2_role == "server"