apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: metallb
  namespace: kube-system
spec:
  chart: oci://registry-1.docker.io/bitnamicharts/metallb
  targetNamespace: metallb-system
  version: "6.3.10"