tls:
  ca:
    cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUUrakNDQXVLZ0F3SUJBZ0lVWmY3aitjUHN0Q2xBYTBzOHNRSVdzSzR2Zk5Fd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF3d0tVMjFwWjNWc1lTQkRRVEFlRncweU5EQTRNalF5TXpFek1UTmFGdzB6TkRBNApNakl5TXpFek1UTmFNQlV4RXpBUkJnTlZCQU1NQ2xOdGFXZDFiR0VnUTBFd2dnSWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElDRHdBd2dnSUtBb0lDQVFDVzVOcnl2QTZNLzN2NS9QSmpaWHNCNnhBbUFMTC9VdHJuZlRLdFRUUWgKM2JsQXEzaDVaZS9mT2pkSEtvUHF0UURtMzhqbm1KSmRMV3dOQWJZTG92ZnJKK2ZFWFcwNzJLUG9BR3hMQ2RCRQpjQWVzVzJhWGcwMEowSjdoRlRLaEY0K3huMVkrYUpqWEgzdzFkUlQ4V2tWYlJQZzdDMmNyUDg3YVMyMkxNWDlSCkpMUzhiNkNPeUs4VmJORk9GSnJWM0h3emNzODNmN2RNMS9zSUJ0ZFBCSWhrTmdQRVdzdXcwQUd1cnJKSWdtR0IKdDhRYTloSGZPdTZhdFcvdTlaRGN2MlNZQW9DTXByYkUwd3JjQUdlUWwvcHNtQ3BQb3lsV0Y1YWhhdkhqTXhYWAppaERyT2UrNWlUNkp5OGdMdi9CNjJyRGZJeW5EMklIdWFBTjlnM0NsdDUyMjY0aFVjRWNRSXVqQWFlRTRqbzVaCkZXQmJ0NEtUK0IzM3A0alhhZURpL09MNHZPd1oyR0h4eXN5SnI2RXpjcExyVEgwVHo1ZzkxSURhM2pJbklUeG8KWUZvYzNvejAzdmYxWGtMTEVZR2pUTmN6aWttb093SnhFSDJ6cWRSbXNsS0RldnBhb2NTeW56NW4wMFpTZHdLVApRUGVia0ZzL1IyYnFuUXVzSHMwc21wV3VwWFprYmlVYUE5UTBDTlhCeTZ3OFVybzJmdndpVGV6YUR6aE5vVmE2CnN1UFRJV014MXZMNUhtYXpyMmpYY0M4cDBIbmRqMUJhNEFDR0o3ZFBqc29HRCtYZE44OW5yNlBoaHVHZU96WTkKMTRhaVQ3WUV0dXp6ck9sOU8zd2oveFpHTWxvY0NxUGdXT2dSN0ErKys1dmN1elVBMDZvRGFRYTk4RmREbjgreQpMd0lEQVFBQm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FnUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WCkhRNEVGZ1FVcnNRZnhLci9janJRNVd5eXRndGlXT1RaUnowd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFDN2cKZW5wT1NZS2FHR3B6Q1ZXY05RRHBQblBjQ29MeUFDT21qeVhYdlNCbjN1T2RXTFBDOWVkQ2lNd2VLYkVFZm82awpQZzdkeldmZ3MrVW1MNHZXSHBOeWhIZllpbXJFc0k4QzRqczcxdnpkVTU0bzdQZVlxLzBjLzViU2NrcFRId3RKCjk5cXB1dCtYNm1tK0NJV3BkdktpNWtJMHFUU1MvbmZzOVVlOHlNYVMvR1hMZkxkYm1HN0h2eGtqb3hPYWhqYzMKSG9xL2NaMG15MVhNNlRMZUlYaHlDZURMeWwxaEVRUU1aZWE1SG16VFlWVkVRckI0TkNoNThtdTROSWhGWXV0ZApwNllVSmI1THJYUkt4V29VeG9pRXZLWm5TdEV3L1h0ZjEyUWhvY0tTemlYSVRtR01KWFJXSEkxTkFkRXhjVUMwCkErcEpoNkRZOXozemlsU1FRNDQ3UFhlZmxFSHVva1RyQzVGTFpqVjBTeFA3WWJSRW1pSWhOdU4vNjJjV0MzRFUKWjRrRmNBSVNZRnNMQ3JxTHFiL0E3RzhCZ3NFeGx0bE1JRFV2ckpJZldzMkR2MHZYY0NUb0M3VG1oQ014Y0l4bQowZHZ6Tjl3WU0xTzAvZjlrOWhHUjVSKzZrcjl1ZnBEZmxKaGNIWWRFMEFFN2FQZHVzN0p2ZDVOM01UOWRiTWZYCi83anNHR00xcndpMk11dDFpV0MwdEdSMW54TzRNRzZtZWNEMjNPVWkxR0VjeVE4L1U4MGorTDVsamM2YS8zMGcKcEpaVmZqVXh6Z1hoY3FudDNmekNlMEQ4UlhtQ3U3Y015dGlKOWI1WkVtN09NTGFBRG9QMnhvcXhGK0x2czFsUwpWc3VQeFpDa2N3SW5QMkU4bHVMekpSN21NbzVrcTBkd3V5ejg1eXUxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBbHVUYThyd09qUDk3K2Z6eVkyVjdBZXNRSmdDeS8xTGE1MzB5clUwMElkMjVRS3Q0CmVXWHYzem8zUnlxRDZyVUE1dC9JNTVpU1hTMXNEUUcyQzZMMzZ5Zm54RjF0TzlpajZBQnNTd25RUkhBSHJGdG0KbDROTkNkQ2U0UlV5b1JlUHNaOVdQbWlZMXg5OE5YVVUvRnBGVzBUNE93dG5Lei9PMmt0dGl6Ri9VU1MwdkcrZwpqc2l2Rld6UlRoU2ExZHg4TTNMUE4zKzNUTmY3Q0FiWFR3U0laRFlEeEZyTHNOQUJycTZ5U0lKaGdiZkVHdllSCjN6cnVtclZ2N3ZXUTNMOWttQUtBakthMnhOTUszQUJua0pmNmJKZ3FUNk1wVmhlV29Xcng0ek1WMTRvUTZ6bnYKdVlrK2ljdklDNy93ZXRxdzN5TXB3OWlCN21nRGZZTndwYmVkdHV1SVZIQkhFQ0xvd0duaE9JNk9XUlZnVzdlQwprL2dkOTZlSTEybmc0dnppK0x6c0dkaGg4Y3JNaWEraE0zS1M2MHg5RTgrWVBkU0EydDR5SnlFOGFHQmFITjZNCjlONzM5VjVDeXhHQm8welhNNHBKcURzQ2NSQjlzNm5VWnJKU2czcjZXcUhFc3A4K1o5TkdVbmNDazBEM201QmIKUDBkbTZwMExyQjdOTEpxVnJxVjJaRzRsR2dQVU5BalZ3Y3VzUEZLNk5uNzhJazNzMmc4NFRhRld1ckxqMHlGagpNZGJ5K1I1bXM2OW8xM0F2S2RCNTNZOVFXdUFBaGllM1Q0N0tCZy9sM1RmUFo2K2o0WWJobmpzMlBkZUdvaysyCkJMYnM4NnpwZlR0OEkvOFdSakphSEFxajRGam9FZXdQdnZ1YjNMczFBTk9xQTJrR3ZmQlhRNS9Qc2k4Q0F3RUEKQVFLQ0FnQWV3QUdjZ05Wb1IzSlE1Z3JSVmE5bEd5MmR5UHV4UzRXL3NnUmZTOEhwZXVGVE8vNWZvdlhvcEZqNgpnRUFFMXlFWmE1WnFGKzRQM2Y5TWdVSkRpZEVERTQxSU40L1lwOVB6Smc3cmxkTGk5MytnMExtTis5eDV1UkYvCnBnMjh4V3Zya3lDRXRGVWRWZFcrb1I4SE5EQTVJc3VCWU5nRCtNdGpNZ2JmWEZWcFNGVXFwNGJ0UWhsb0FOYUEKbG5OZFRNTGt5eXRPVUpFZXNFOEFla0JyWW0yWEdtalhIWGV3RHh1Z3FRbzgrNUQ2V2VRMWFGc0pCbDMwbWkvMgozd1ZIN3hzRlhWRXNHSmRiY2ZTZkU5Z0hIK21STXN0QWttd01sdDhFQXlMTEhiQ0FUYXNYL0tVTlJ0by9RNDkvClVYeWsxS2RCdWMwN2s0WWErd2huRGgrcExjdU9XTUprS241NllTUmM4L3NBNFJYRkFHZ0pNcDJrRzlTK3VVTHkKVEt0L2FOdzlSY25vSXNaVTdvQ21HQm15MEdCcjRKVks3QUtZZWJPdi9Mb2JKS1FyU096c253V1VZYUVuQnBSVwo2dGlTdjBiYW9HV3U5Z3JpVUF5YU9lQU9rOFBhM0t1TysraHZObnZ6eUtpSGZucDRiNFh6WHlqMzh0d0xzaWk0CmRtYmUvcDY1Tk1oNG94amxMUmFlRVMyN3Mwek1ZL0xaWkdwaUVqS3RLZjJhcWNoZVl0SWxWcm9NaTJva2R0cUQKcUF4Q1BkNStYeEFuUy9hd1dWanozWUllc0RYdVM5VlluVE43TGhyOEwwdytNR1VGUlV6UEtiT2pkWndTKzE2SQpSZ3RocW8wY1NWQnB0bU9IRm9VNVdlcVI2QTZWd0srQUtkZUNoYmZrK3FWQjlRVnRMUUtDQVFFQXhrWUg3cXNQCjFUZHg5RS9uL1RmWjAyZVBWYyt6ZGFjYzBMTkdzaFlmSlJRU3lkWlRTMG14a2Q2cWtvWkpYZzA2OHk1Z1hoN3YKSVRIaWt1dkZraE5DeUphN3VzVU04WEVmZjhvT0xtZ0VLNnUzcUppYkQ2YzJqWE9yZ01RWjV4S0N2ekZvUk1KbgpwQ0hnYVo5WHVnRUhkZjZhMlBmWkF6dXlqRFVJWTU1YmVBNDhNVGVuejRLMWxqN2lkNWs3TjFvaG9SeDBxTzlQCjMyRHNQMmxxeXlUNnNQQ0IxUjVLMUQ5UXdkTHVUNXNHUmduMWU4VSsrZmE5QVRlZm5VdlFoNUVnMitpNUZubUkKV3NIY3JvUDhrZ3gzVzZpaXRKRnBWL05QRG85Q3ZKYk9wZTBjazNrY2dYd3RTQUE4Rk44YU1JNC96QjhWejh0Rwo0dmZQZWRucTdUUHVjd0tDQVFFQXd0TjRXd2ZmVGFGbEpkSEhvM0xyK2RuZVc4SjhNWmpESU1xTlVxeW84WGl5ClZFaUJhSURkMkZsWWJJMHE3SzAvUE5SMHdmWGtGMVdSMTQ0Y1dSSmxTOXAzY1dPSXJXaWRKOW1PWDBDVVBFQ2oKUnVKQ1BkalVuWWY2KzVUME5qcUptbVZFL1BwcG1BNlVPWGVYeUYwa2c5eHZTUjM0YlRVNVJQbzBKckRIWTFlSwpKOFU0MFhvcHFLeEo1UGQzR2JpclYyV1doNzQwUTdFRm5ZamFOQ0NOa0NPWlduY2VJUlJtekE4N2xUb296SU9hClZVQlpKM2dSb0R1K0NnZ3psZSt4TFBycks5UUN0R2R6eTJQclBDdE9QR3RNREY5NmoxcmFPNkJ3U2lId1lhV2YKMTI0L1pmQkk2K3lleHdYd3hmSHRwVS9zZHgvdUNrZ2RwMjVSRXJEaVZRS0NBUUE0bnFrSE8reFNpL25MdGNIZQo2c01XZnIxTTJQbzdmOVJYdU1wWWNyN0VITjVjcXdxd05rUXlEcThSRnEzKzRMSlQzWXVCZFQzK2NidHREMDBsCk1NRGlmVUR3emZLclJBMmx0WEtsUitqZys3Ri93TXlQQk1Zc1VMcktFN1g5NmFoU3B1NUtyR1ZpVnBZNk0xbWUKOFVwTEpNRGRjckdUSGNvWUJkRDJlYk5QTG1sNytKUEFTMmhGbG9HZmU2K1FWL25BZzFyQkgwM2swVTNGc2ZuZwpOeGdyelJLV1pJY2o0MHpSZk1XM0QrTVR2eVpPQ1A2NTdQNytTUDhZc1J6RWllb2pRbXNRZ3ZZd1RLb1RYL2VSClVXUUlWYmpZN2FseWh6V3RSN1hjR3dpNkUyTVVyZ0k0NjlnV2RwS3h0eUJJZTJhMmlLMzIzK3JIUjlNRXpma3IKY2FnSEFvSUJBQUtkdEZBRW13ci96OHZpTlR3TW52NkwzbUI5REEzZWIwQlJkL1JVUFRDQTNtUWpWUm1DSVhoMgpPcW02ZTRrU0NuZFdvdnEzd29oTnJkZW5JTnBSVk9yZjFCckJxMlFvczNPRmlGUGZHaDUwLzd4RDdYL0hHWlBECjc2clJKVFpWTXVQUDJFMU5UMzJyTkhKUkdNaW45NFdOd0RETEpqclJMQ093K0dKTW5XRElIQ0xNa3lhODdUSkcKbmZkbEcwUk5Kbi9WN1YrRlBrNXFZaGpyYllLbHJVRHlPV3p0aklvRkxCd3hXQ3Q0ekhOeWtPLzBIVDVhYm1JbwphelRYUjFvTURlVDh1WXV0SFJ3dkIyOER1SFRtWC9hUHVrV3dRb1VLUTBQcHM1aExQRjhUU2tJcVNNK2xtbFVRCnFGRWowMGZWSjh2QWR2eGlnVi9CK0NQM1p6OUpBTUVDZ2dFQkFJdndKK0U4S2dTczNaMXRtL0F5d2xYRE1UbDIKWDc4aXBoOEpnQjZJR3ptYVV2NTFiTkxJaUI0VWxVaTEyVGE0bko2ak5TTm15VG9wZkRLN28ra094L3d6QllCawp2NUFTNkNoOXRBSmZLM2FYNDUxUEFSV0NkR0xvSCtzWGNzZHcwaVFsaVREVnBBazV3Y2dLeUw5NE11LzM3YkxmCjFUb3gxYTMzTGxZM3JpZGxMZmVnK2ZXTDRjOEQ0SVp0SU5VRWZNNFVkdkVOa3pnN1hmamwwd2RiWU9OR0Izek0KSnBjK0k0NE5zOWpEdjUzV2ZsbEg1TWdoK1FCaGZBRWJGSFNHc0w0NnllNjlyTElsOWJhdDByTlNlNnVneEtYegppZTJGUk1tS0VRVmxLQjVTOUkxQ0hvTlczQnpvQVUzQzJLQmRSQzVKenFhd3Qyb2g2TWdYclRBL0xJMD0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
bpf:
  masquerade: true
cluster:
  name: cilium-demo-cluster
  id: 0
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
dashboards:
  enabled: true
hubble:
  enabled: true
  metrics:
    enabled:
    - dns:query;ignoreAAAA
    - drop
    - tcp
    - flow
    - icmp
    - http
    - "flow:sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
    - "kafka:labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
    - "httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
    dashboards:
      enabled: true
    serviceMonitor:
      enabled: true
  relay:
    enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
  ui:
    enabled: true
    baseUrl: "/"
    ingress:
      enabled: true
      hosts: 
      - hubble.cilium-demo-cluster.kubula.internal
version: 1.16.1
operator:
  replicas: 1
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  dashboards:
    enabled: true
envoy:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
    service:
      type: NodePort
      nodePort: 32379
    tls:
      authMode: cluster
      server:
        extraDnsNames:
          - "*.kubula.internal"
clustermesh:
  useAPIServer: true
  enableEndpointSliceSynchronization: true
  apiserver:
    service:
      type: LoadBalancer
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
kubeProxyReplacement: true
ipam:
  mode: kubernetes
socketLB:
  enabled: true
  hostNamespaceOnly: true
ipv4:
  enabled: true
nodePort:
  enabled: true
authentication:
  mutual:
    spire:
      enabled: true
      install:
        enabled: true
        server:
          dataStorage:
            enabled: false
encryption:
  enabled: false
  type: wireguard
  nodeEncryption: true
  strictMode:
    enabled: false
    allowRemoteNodeIdentities: true
    cidr: 10.45.0.0/16


