k8s-cluster:
  hosts:
    # cp1:
    #   ansible_host: 192.168.1.100
    #   rke2_server_address: 192.168.1.100
    #   cilium_k8s_hostname: controlplane1.cilium-demo-cluster1.kubula.interal
    #   # ansible_become: yes
    #   rke2_cluster_name: "cilium-demo-cluster1"
    #   rke2_role: server
    #   rke2_cluster_cidr: 10.42.0.0/16
    #   rke2_service_cidr: 10.96.0.0/16
    #   cilium_master: true
    #   cilium_install: true
    #   cilium_default_domain: "cilium-demo-cluster1.kubula.internal"
    #   cilium_mesh_cluster_id: "01"
    #   cilium_apiserver_port: 32379
    #   cilium_peer_apiserver_port: 32380
    #   cilium_peer_cluster_name: cilium-demo-cluster2
    #   cilium_peer_cluster_address: cilium-demo-cluster2.kubula.internal
    #   rke2_egress_selector_mode: "disabled"
    #   rke2_protect_kernel_defaults: true
    #   cilium_ipam_mode: "cluster-pool"
    # w1:
    #   ansible_host: 192.168.1.101
    #   rke2_cluster_name: "cilium-demo-cluster2"
    #   rke2_role: agent
    #   rke2_server_address: "192.168.1.101"
    #   cilium_install: false
    #   cilium_master: false
    #   init_install_kubectl: false
    #   init_install_k9s: false
    w2:
      ansible_host: 192.168.1.102
      rke2_cluster_name: "cilium-demo-cluster2"
      rke2_role: agent
      rke2_server_address: "192.168.1.102"
      cilium_install: false
      cilium_master: false
      init_install_kubectl: false
      init_install_k9s: false