apiVersion: v1
kind: Service
metadata:
  annotations:
    service.cilium.io/global: "true"
    service.cilium.io/global-sync-endpoint-slices: "true"
  labels:
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: lgtm-distributed
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: 2.9.6
  name: lgtm-distributed-loki-gateway
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: lgtm-distributed
    app.kubernetes.io/name: loki
  type: ClusterIP
