apiVersion: v1
kind: Service
metadata:
  annotations:
    service.cilium.io/global: "true"
    service.cilium.io/global-sync-endpoint-slices: "true"
  labels:
    app.kubernetes.io/component: nginx
    app.kubernetes.io/instance: lgtm-distributed
    app.kubernetes.io/name: mimir
    app.kubernetes.io/version: 2.12.0
  name: lgtm-distributed-mimir-nginx
  namespace: monitoring
spec:
  ports:
  - name: http-metric
    port: 80
    protocol: TCP
    targetPort: http-metric
  selector:
    app.kubernetes.io/component: nginx
    app.kubernetes.io/instance: lgtm-distributed
    app.kubernetes.io/name: mimir
  type: ClusterIP
