---
# Main task file for the rke2 role

# Include tasks for configuring RKE2 server/agent
- include_tasks: configure.yaml

# Include Helm chart installation tasks only on the servers
- include_tasks: helm.yaml
  when: rke2_role == "server"