apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: metallb-system
spec:
  avoidBuggyIPs: true
  addresses:
  - 192.168.1.200-192.168.1.210
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: main-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - main-pool
---
# apiVersion: metallb.io/v1beta2
# kind: BGPPeer
# metadata:
#   name: default
#   namespace: metallb-system
# spec:
#   myASN: 64790
#   peerASN: 64791
#   peerAddress: 192.168.20.64
# ---
# apiVersion: metallb.io/v1beta1
# kind: BGPAdvertisement
# metadata:
#   name: default
#   namespace: metallb-system
# spec:
#   ipAddressPools:
#   - default