
apiVersion: v1
kind: Namespace
metadata:
  name: x-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x-web
  labels:
    app: x-web
  namespace: x-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: x-web
  template:
    metadata:
      labels:
        app: x-web
    spec:
      containers:
      - name: x-web
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: x-web
  namespace: x-web
  annotations:
    service.cilium.io/global-sync-endpoint-slices: "true"
    service.cilium.io/global: "true"
spec:
  selector:
    app: x-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: x-web
  namespace: x-web
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: x-web.cluster1.kubula.internal
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: x-web
            port:
              number: 80