---
# vars file for init
init_user_name: "rke2"
init_user_password: "$6$w2Xiyvj66j623aDP$OKE6Ds7dEEdXYIzXlPeuyclaMul7.ym3oRIIX3Nr2EtA/tSTzdjsgzCpxbpZjd6umAq.vODWo6DAy07KyAI9E0"
init_packages:
- bash-completion
- curl
- git
- rsync
- screen
- tcpdump
- vim
- wget
- nano
- tmux
- jq
- vim-common
- iscsi-initiator-utils
- unzip
- tar
- nfs-utils
- redhat-lsb-core.x86_64
- frr
init_install_kubectl: true
init_install_k9s: true
init_k9s_version: "v0.32.5"