# modify_kubeconfig.yaml
---
- name: Read kubeconfig file content for cluster {{ rke2_cluster_name }}
  slurp:
    src: "{{ files_path }}/{{ rke2_cluster_name }}-kubeconfig"
  register: kubeconfig_file

- name: Parse kubeconfig and extract certificate-authority-data for the first cluster
  set_fact:
    certificate_authority_data: "{{ (kubeconfig_file.content | b64decode | from_yaml).clusters[0].cluster['certificate-authority-data'] }}"

- name: Parse and modify kubeconfig for cluster {{ rke2_cluster_name }}
  set_fact:
    modified_kubeconfig: >
      {{
        (kubeconfig_file.content | b64decode | from_yaml) |
        combine({
          'clusters': (kubeconfig_file.content | b64decode | from_yaml)['clusters'] |
          map('combine', {
            'cluster': {
              'server': 'https://' ~ rke2_server_address ~ ':6443',
              'certificate-authority-data': certificate_authority_data
            },
            'name': rke2_cluster_name
          }) | list,
          'contexts': (kubeconfig_file.content | b64decode | from_yaml)['contexts'] |
          map('combine', {
            'context': {
              'cluster': rke2_cluster_name,
              'user': 'rke2@' ~ rke2_cluster_name
            },
            'name': rke2_cluster_name
          }) | list,
          'users': (kubeconfig_file.content | b64decode | from_yaml)['users'] |
          map('combine', {
            'name': 'rke2@' ~ rke2_cluster_name
          }) | list
        })
      }}

- name: Save modified kubeconfig for cluster {{ rke2_cluster_name }} back to file
  copy:
    dest: "{{ files_path }}/{{ rke2_cluster_name }}-kubeconfig"
    content: "{{ modified_kubeconfig | to_nice_yaml(indent=2) }}"
