---
grafana:
  # -- Deploy Grafana if enabled. See [upstream readme](https://github.com/grafana/helm-charts/tree/main/charts/grafana#configuration) for full values reference.
  enabled: true
  adminPassword: SuperSecret1
  serviceMonitor:
    enabled: true 
    namespace: "monitoring"
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: '1'
      memory: 2Gi

  # -- Grafana data sources config. Connects to all three by default
  datasources:
    datasources.yaml:
      apiVersion: 1
      # -- Datasources linked to the Grafana instance. Override if you disable any components.
      datasources:
        # https://grafana.com/docs/grafana/latest/datasources/loki/#provision-the-loki-data-source
        - name: Loki
          uid: loki
          type: loki
          url: http://{{ .Release.Name }}-loki-gateway
          isDefault: false
        # https://grafana.com/docs/grafana/latest/datasources/prometheus/#provision-the-data-source
        - name: Mimir
          uid: prom
          type: prometheus
          url: http://{{ .Release.Name }}-mimir-nginx/prometheus
          isDefault: true
        # https://grafana.com/docs/grafana/latest/datasources/tempo/configure-tempo-data-source/#provision-the-data-source
        - name: Tempo
          uid: tempo
          type: tempo
          url: http://{{ .Release.Name }}-tempo-query-frontend:3100
          isDefault: false
          jsonData:
            tracesToLogsV2:
              datasourceUid: loki
            lokiSearch:
              datasourceUid: loki
            tracesToMetrics:
              datasourceUid: prom
            serviceMap:
              datasourceUid: prom
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
      dashboards:
        default:
          prometheusViewsNodes:
            gnetId: 15759
            revision: 28
            datasource: Prometheus

loki:
  # -- Deploy Loki if enabled. See [upstream readme](https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed#values) for full values reference.
  enabled: true
  global:
    dnsService: "rke2-coredns-rke2-coredns"
  serviceMonitor:
    enabled: true
    namespace: monitoring
  storageConfig:
    aws:
      s3: "s3://mimir:supersecret@minio.minio.svc.cluster.local:9000/mimir-logs"
      s3forcepathstyle: true
      insecure: true

# -- Mimir chart values. Resources are set to a minimum by default.
mimir:
  # -- Deploy Mimir if enabled. See [upstream values.yaml](https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yaml) for full values reference.
  enabled: true
  global:
    dnsService: "rke2-coredns-rke2-coredns"
  runtimeConfig:
    overrides:
      anonymous:
        ingestion_tenant_shard_size: 9
        max_global_series_per_user: 0
        max_fetched_series_per_query: 0  
        compactor_blocks_retention_period: 1d
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: "minio.minio.svc.cluster.local:9000"
          region: "us-east-1"
          # bucket_name: "mimir-tsdb"
          access_key_id: "mimir" # This is a secret injected via an environment variable
          secret_access_key: "supersecret" # This is a secret injected via an environment variable
          http:
            insecure_skip_verify: true
      ruler_storage:
        backend: s3
        s3:
          bucket_name: "mimir-ruler"
      alertmanager_storage:
        backend: s3
        s3:
          bucket_name: "mimir-alertmanager"
      blocks_storage:
        backend: s3
        s3:
          bucket_name: "mimir-tsdb"
    # limits:
    #   max_global_series_per_user: 20000000
    #   ingestion_rate: 200000
    #   ingestion_burst_size: 1000000
    #   out_of_order_time_window: 5m
  metaMonitoring:
    dashboards:
      enabled: true
    serviceMonitor:
      enabled: true
      # clusterLabel: "cilium-cluster3"
      namespace: monitoring
  alertmanager:
    enabled: false
    resources:
      requests:
        cpu: 20m
  compactor:
    resources:
      requests:
        cpu: 20m
    persistentVolume:
      enabled: false
  distributor:
    resources:
      requests:
        cpu: 20m
  ingester:
    replicas: 2
    zoneAwareReplication:
      enabled: false
    resources:
      requests:
        cpu: 20m
    persistentVolume:
      enabled: false
  overrides_exporter:
    resources:
      requests:
        cpu: 20m
  querier:
    replicas: 1
    resources:
      requests:
        cpu: 20m
  query_frontend:
    resources:
      requests:
        cpu: 20m
  query_scheduler:
    replicas: 1
    resources:
      requests:
        cpu: 20m
  ruler:
    enabled: false
    resources:
      requests:
        cpu: 20m
  store_gateway:
    zoneAwareReplication:
      enabled: false
    resources:
      requests:
        cpu: 20m
    persistentVolume:
      enabled: false
  minio:
    enabled: false
    resources:
      requests:
        cpu: 20m
  rollout_operator:
    resources:
      requests:
        cpu: 20m


tempo:
  # -- Deploy Tempo if enabled.  See [upstream readme](https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/README.md#values) for full values reference.
  enabled: false
  global:
    dnsService: "rke2-coredns-rke2-coredns"
  ingester:
    replicas: 1

grafana-oncall:
  # -- Deploy Grafana OnCall if enabled. See [upstream values.yaml](https://github.com/grafana/oncall/blob/dev/helm/oncall/values.yaml) for full values reference.
  enabled: false
